### ISSUE TITLE
How to run the system

### ISSUE THREAD

**Issue by AngelGorospe** [nsadisha/Report-Generation-System#15]
Hello! I am new to programming. How can I run this kind of system?

**Comment by nsadisha** [comment]
Open this project in an IDE.
Then, create a database and add credentials to the Main.java file.
Create tables and edit queries in [reports](https://github.com/nsadisha/Report-Generation-System/blob/master/src/main/java/com/rgsystem/report/reports/)

Eg: [Click here](https://github.com/nsadisha/Report-Generation-System/blob/180c791eb65044732de8400e9358ccdf10b7eba9/src/main/java/com/rgsystem/report/reports/DailySalesReport.java#L27)
